name: Build & Release APK

on:
  push:
    tags:
      - 'v*' # 仅在推送以v开头的tag时触发发布
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Convert gradlew to Unix format
      run: |
        sudo apt-get update && sudo apt-get install dos2unix -y
        dos2unix gradlew

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/*.apk

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release-apk

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.apk"
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: "自动构建发布"
